[debug]
DEBUG = 1

[network]
IP = '127.0.0.1'
IN_PORT = 8000
OUT_PORT = 7000

[encoders]
    [encoders.e0]
        PINS = [3, 5]
        ADDRESS = "/rotary_0"
    [encoders.e1]
        PINS = [8, 10]
        ADDRESS = "/rotary_1"
    [encoders.e2]
        PINS = [19, 21]
        ADDRESS = "/rotary_2"
    [encoders.e3]
        PINS = [18, 22]
        ADDRESS = "/rotary_3"
    [encoders.e4]
        PINS = [39, 41]
        ADDRESS = "/rotary_4"
    [encoders.e5]
        PINS = [40, 42]
        ADDRESS = "/rotary_5"

[buttons]
    [buttons.b0]
        PIN = 12
        ADDRESS = "/button_0"

[i2c]
CLK = 13
DIO = 11
